name: EasyLM
channels:
    - pytorch
    - nvidia
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - numpy==1.26.4
    - scipy
    - matplotlib
    - seaborn
    - jupyter
    - tqdm
    - pytorch
    - pytorch-cuda=12.4
    - pip:
        - jax[cuda12]==0.4.28
        - flax==0.8.3
        - git+https://github.com/deepmind/optax.git
        - transformers==4.41.0
        - torch==2.3.0
        - sentencepiece
        - datasets
        - mlxu >= 0.1.13
        - einops
        - gcsfs
        - google-cloud-storage
        - neural-tangents
        - wandb==0.17.4
        - requests
        - lm-eval
        - pydantic
        - fastapi
        - uvicorn
        - gradio